# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171019_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('vote', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='option',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='option',
            name='vote',
        ),
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AddField(
            model_name='candidate',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Option'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Poll'),
        ),
        migrations.AddField(
            model_name='poll',
            name='options',
            field=models.ManyToManyField(through='main.Candidate', to='main.Option'),
        ),
    ]
