# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20171019_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='name',
        ),
        migrations.AlterField(
            model_name='poll',
            name='options',
            field=models.ManyToManyField(related_name='poll_options', through='main.Candidate', to='main.Option'),
        ),
    ]
