# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_option_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choiceVote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Choice')),
            ],
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='option',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='author',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='description',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='name',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='options',
        ),
        migrations.AddField(
            model_name='poll',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='question',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.AddField(
            model_name='vote',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Poll'),
        ),
        migrations.AddField(
            model_name='choice',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Poll'),
        ),
    ]
